---
title: "Results Overview"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(magrittr)
library(dplyr)
library(knitr)
library(kableExtra)
load("../tmp/results-all_2021-04-26--20-24-12---f25fcea3.Rdata")
```


# CFA

## MLR Estimation

```{r, results='asis'}
wch_res <- res_cfa_mlr
wch_res %>% 
  select(model, npar, cfi.robust, rmsea.robust, status) %>%
  mutate_at(c("cfi.robust", "rmsea.robust"), ~ round(.x, 3)) %>%
  kable() %>%
  kable_styling() %>%
  row_spec(which.max(wch_res[["cfi.robust"]]), bold = TRUE, background = "lightgreen") %>%
  row_spec(which.min(wch_res[["rmsea.robust"]]), bold = TRUE, background = "lightgreen")
```

## WLSMV Estimation

```{r}
wch_res <- res_cfa_ordinal
wch_res %>% select(model, npar, cfi.scaled, rmsea.scaled, status) %>%
  mutate_at(c("cfi.scaled", "rmsea.scaled"), ~ round(.x, 3)) %>%
  kable() %>%
  kable_styling() %>%
  row_spec(which.max(wch_res[["cfi.scaled"]]), bold = TRUE, background = "lightgreen") %>%
  row_spec(which.min(wch_res[["rmsea.scaled"]]), bold = TRUE, background = "lightgreen")

```

## Warnings

```{r}
res_cfa_mlr %>% filter(status != "success") %>% pull(status_msg) %>% cat()
```


```{r}
res_cfa_ordinal %>% filter(status != "success") %>% pull(status_msg) %>% cat()
```


# Measurement Invariance

## MLR Estimation

```{r}
wch_res <- res_mi_mlr
is_groupmodel <- grepl("group", wch_res[["constraint"]])
is_groupmodel_red <- is_groupmodel & (wch_res[["cfi.robust"]] < 0.95)
is_groupmodel_green <- is_groupmodel & (wch_res[["cfi.robust"]] >= 0.95)
is_invariant <- (wch_res[["cfi_robust_diff"]] > 0.01)

wch_res %>% 
  select(model, group, grps, grps_n, constraint, npar, contains("cfi")) %>%
  mutate(across(contains("cfi"), ~ round(.x, 3))) %>%
  kable() %>%
  kable_styling() %>%
  row_spec(which(is_groupmodel), bold = TRUE) %>%
  row_spec(which(is_groupmodel_green), background = "green") %>%
  row_spec(which(is_groupmodel_red), background = "red") %>%
  row_spec(which(is_invariant), background = "#FFC3C3")

```

## WLSMV Estimation

```{r}
wch_res <- res_mi_ordinal
is_groupmodel <- grepl("group", wch_res[["constraint"]])
is_groupmodel_red <- is_groupmodel & (wch_res[["cfi.scaled"]] < 0.95)
is_groupmodel_green <- is_groupmodel & (wch_res[["cfi.scaled"]] >= 0.95)
is_invariant <- (wch_res[["anova_p"]] < 0.05)

wch_res %>% 
  select(model, group, grps, grps_n, constraint, npar, cfi.scaled, anova_chisq, anova_df, anova_chisq_per_df, anova_p) %>%
  mutate(across(c(cfi.scaled, anova_chisq, anova_chisq_per_df, anova_p), ~ round(.x, 3))) %>%
  kable() %>%
  kable_styling() %>%
  row_spec(which(is_groupmodel), bold = TRUE) %>%
  row_spec(which(is_groupmodel_green), background = "green") %>%
  row_spec(which(is_groupmodel_red), background = "red") %>%
  row_spec(which(is_invariant), background = "#FFC3C3")
```

## Warnings

```{r}
res_mi_mlr %>% filter(status != "success") %>%
  group_by(status, model, group) %>%
  count() %>%
  select(n, everything()) %>%
  kable() %>%
  kable_styling()
```

```{r}
res_mi_mlr %>% filter(status != "success") %>% pull(status_msg) %>% unique() %>% cat()
```


```{r}
res_mi_ordinal %>% filter(status != "success") %>%
  group_by(status, model, group) %>%
  count() %>%
  select(n, everything()) %>%
  kable() %>%
  kable_styling()
```

```{r}
res_mi_ordinal %>% filter(status != "success") %>% pull(status_msg) %>% unique() %>% cat()
```
